ARG BASE=twinet/switch:msc-base
FROM ${BASE}
RUN apk add --no-cache coreutils procps iptables python3
LABEL org.opencontainers.image.title="twinet-msc-switch" \
      org.opencontainers.image.source="https://github.com/HongyuHe/Twinet"
