package cli

import (
	"context"
	"strings"
	"testing"
	"time"

	"github.com/HongyuHe/twinet/internal/model"
	"github.com/HongyuHe/twinet/internal/nos"
)

// The whole point of these tests is that a student AS running BIRD can be
// saved, restored and regraded -- and that no FRR binary is ever run inside a
// BIRD router on the way. `twinet save` used to run `vtysh -c "show
// running-config"` on every router unconditionally, and the batch loader used
// to reload every submission through FRR's exact-reload tool; both failed the
// whole group the moment a course put BIRD in a student AS.

const birdSavedConfig = `# Generated by Twinet; do not edit while deployed.
router id 3.151.0.1;

protocol device {}
protocol kernel kernel4 { ipv4 { import none; export all; }; }
protocol static own4 { ipv4; route 3.0.0.0/8 reject; }
protocol bgp ebgp_ext_2_ALL {
  local as 3;
  neighbor 179.1.2.2 as 2;
  ipv4 { import filter import_ebgp_ext_2_ALL; export filter export_ebgp_ext_2_ALL; };
}
`

// birdRouterExec answers a BIRD router's reads and records every command, so a
// test can assert both the content and that nothing FRR-shaped was run.
func birdRouterExec(t *testing.T, seen *[]string) func(context.Context, string, []string) (execResult, error) {
	t.Helper()
	return func(_ context.Context, _ string, cmd []string) (execResult, error) {
		*seen = append(*seen, strings.Join(cmd, " "))
		switch {
		case len(cmd) >= 2 && cmd[0] == "cat" && cmd[1] == "/etc/bird/bird.conf":
			return execResult{Stdout: birdSavedConfig}, nil
		case len(cmd) > 0 && cmd[0] == "birdc":
			return execResult{Stdout: "BIRD 2.0.12 ready.\nDaemon is up and running\n"}, nil
		default:
			return execResult{}, nil
		}
	}
}

func assertNoFRRBinary(t *testing.T, commands []string) {
	t.Helper()
	for _, command := range commands {
		for _, forbidden := range []string{"vtysh", "frr-reload.py", "frrinit.sh", "/etc/frr"} {
			if strings.Contains(command, forbidden) {
				t.Fatalf("an FRR command reached a BIRD router: %q contains %q", command, forbidden)
			}
		}
	}
}

func birdStudentTopology() (*model.Topology, *model.Device) {
	router := &model.Device{
		ID: "as3/ATL", Name: "ATL", Kind: model.KindRouter, ASN: 3, NOS: "bird",
		Container: "twinet-as3-ATL",
	}
	top := &model.Topology{
		Name: "cos461", Hash: "abc123",
		Devices: map[string]*model.Device{router.ID: router},
		ASes: map[int]*model.AS{
			3: {ASN: 3, Role: model.RoleStudent, OwnerGroup: "group3",
				Routers: []*model.Device{router}, Devices: []*model.Device{router}},
		},
	}
	return top, router
}

func TestSaveAndRestoreOfABIRDStudentAS(t *testing.T) {
	t.Setenv("TWINET_PKI", t.TempDir())
	key, err := submissionKey()
	if err != nil {
		t.Fatal(err)
	}
	top, router := birdStudentTopology()

	var saved []string
	out := t.TempDir()
	path, err := saveAS(context.Background(), top, 3, out, birdRouterExec(t, &saved), key)
	if err != nil {
		t.Fatalf("a BIRD student AS could not be saved: %v", err)
	}
	assertNoFRRBinary(t, saved)

	// readBundle is the loader's own reader: it verifies the signature and
	// every checksum before returning, so this also proves the manifest
	// signature covers the recorded NOS.
	bundle, files, err := readBundle(path)
	if err != nil {
		t.Fatalf("the saved BIRD archive did not verify: %v", err)
	}
	if bundle.NOS["ATL.conf"] != "bird" {
		t.Fatalf("the archive does not record which NOS it was captured from: %#v", bundle.NOS)
	}
	if !strings.Contains(string(files["ATL.conf"]), "protocol bgp ebgp_ext_2_ALL") {
		t.Fatalf("the archive does not carry the BIRD configuration: %q", files["ATL.conf"])
	}

	var restored []string
	restore := nos.BIRDStartWaitForTest(50 * time.Millisecond)
	defer restore()
	n, err := restoreBundle(context.Background(), top, bundle, files, birdRouterExec(t, &restored))
	if err != nil {
		t.Fatalf("a BIRD archive could not be restored: %v", err)
	}
	if n != 1 {
		t.Fatalf("restored %d configurations, want 1", n)
	}
	assertNoFRRBinary(t, restored)
	joined := strings.Join(restored, "\n")
	if !strings.Contains(joined, "birdc -s /run/bird.ctl configure") {
		t.Fatalf("the restore did not ask BIRD to adopt the configuration:\n%s", joined)
	}
	if !strings.Contains(joined, "> /etc/bird/bird.conf") {
		t.Fatalf("the restore did not install the configuration where BIRD reads it:\n%s", joined)
	}
	_ = router
}

// An archive captured from one NOS must never be loaded into another. Silently
// skipping it produces a device with no configuration at all, which grades
// exactly like a student who wrote none.
func TestAnArchiveForAnotherNOSIsRefusedByName(t *testing.T) {
	top, router := birdStudentTopology()
	var seen []string
	exec := birdRouterExec(t, &seen)

	err := loadRouterConfigBody(context.Background(), exec, router, "frr", "router bgp 3\n")
	if err == nil {
		t.Fatal("an FRR configuration was loaded into a BIRD router")
	}
	if !nos.IsConfigMismatch(err) {
		t.Fatalf("the refusal is not a typed configuration mismatch: %v", err)
	}
	for _, want := range []string{"frr", "bird", router.ID} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the refusal does not name %q: %v", want, err)
		}
	}
	assertNoFRRBinary(t, seen)

	// And the reverse: an archive that records nothing is FRR by construction,
	// so it must not be assumed to belong to a device running something else.
	err = loadRouterConfigBody(context.Background(), exec, router, "", "router bgp 3\n")
	if err == nil || !nos.IsConfigMismatch(err) {
		t.Fatalf("an archive with no recorded NOS was accepted for a BIRD router: %v", err)
	}
	_ = top
}

// applySubmission is the batch-grading path: it must select the loader from the
// device's provider and refuse an archive written for another.
func TestSubmissionLoadingSelectsTheProvider(t *testing.T) {
	top, router := birdStudentTopology()
	var seen []string
	exec := birdRouterExec(t, &seen)

	restore := nos.BIRDStartWaitForTest(50 * time.Millisecond)
	defer restore()

	good := submission{
		Group: "group3", AS: 3,
		Files: map[string]string{"ATL": birdSavedConfig},
		NOS:   map[string]string{"ATL": "bird"},
	}
	if err := applySubmission(context.Background(), exec, top, good); err != nil {
		t.Fatalf("a BIRD submission could not be loaded: %v", err)
	}
	assertNoFRRBinary(t, seen)
	if !strings.Contains(strings.Join(seen, "\n"), "birdc -s /run/bird.ctl configure") {
		t.Fatalf("the submission was not adopted by the running daemon:\n%s", strings.Join(seen, "\n"))
	}

	seen = nil
	bad := submission{
		Group: "group3", AS: 3,
		Files: map[string]string{"ATL": "router bgp 3\n"},
		NOS:   map[string]string{"ATL": "frr"},
	}
	err := applySubmission(context.Background(), exec, top, bad)
	if err == nil || !nos.IsConfigMismatch(err) {
		t.Fatalf("an FRR submission was loaded into a BIRD AS: %v", err)
	}
	assertNoFRRBinary(t, seen)
	_ = router
}

// The platform baseline a reset installs is rendered by the device's own
// provider too, or a reset would leave a BIRD router holding FRR text.
func TestPlatformBaselineUsesTheDeviceProvider(t *testing.T) {
	_, router := birdStudentTopology()
	var seen []string
	if err := loadPlatformConfig(context.Background(), birdRouterExec(t, &seen), router,
		birdSavedConfig); err != nil {
		t.Fatalf("a BIRD platform baseline was refused: %v", err)
	}
	assertNoFRRBinary(t, seen)
}
