package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/HongyuHe/twinet/internal/model"
	"github.com/HongyuHe/twinet/internal/svc"
)

type birdPeer struct {
	name, address string
	asn           int
	relationship  model.Relationship
	internal      bool
	routeServer   bool
	slow          bool
	ixpRecipients []int
	sameRegion    []int
}

// BirdRouter renders the BIRD 2 configuration used by a router that declares
// `nos: bird`, in a staff-run or a student-owned AS alike.
//
// A student-owned BIRD router is now supported end to end: `twinet save`
// captures BIRD's own configuration file, the archive records which NOS it was
// captured from, and the loader refuses an archive written for another rather
// than installing syntax the daemon cannot read. Manifest validation reports
// the remaining boundary per feature -- BIRD declares no RPKI, MPLS/LDP, VRF,
// multicast or tunnel support here -- before a deploy is attempted.
//
// The configuration is derived from the same topology facts as FRR: kernel
// addresses are installed by birdRouterCommands, BIRD owns OSPF/BGP and the
// relationship policy, and Linux owns forwarding.
func BirdRouter(top *model.Topology, d *model.Device) (RouterConfig, error) {
	if d == nil || !d.IsRouter() {
		return RouterConfig{}, fmt.Errorf("BIRD configuration needs a router")
	}
	as := top.ASes[d.ASN]
	if as == nil {
		return RouterConfig{}, fmt.Errorf("%s belongs to unknown AS %d", d.ID, d.ASN)
	}
	if as.Role == model.RoleIXP {
		return RouterConfig{}, fmt.Errorf("%s is an IXP route server; BIRD route-server rendering is not supported", d.ID)
	}

	var platform, ospf, bgp strings.Builder
	platform.WriteString("# Generated by Twinet; do not edit while deployed.\n")
	fmt.Fprintf(&platform, "router id %s;\n\n", routerID(d))
	platform.WriteString("protocol device {}\n\n")
	platform.WriteString("protocol direct direct4 { ipv4; }\n")
	platform.WriteString("protocol direct direct6 { ipv6; }\n")
	platform.WriteString("protocol kernel kernel4 { ipv4 { import none; export all; }; }\n")
	platform.WriteString("protocol kernel kernel6 { ipv6 { import none; export all; }; }\n\n")
	if as.Block != "" {
		fmt.Fprintf(&bgp, "protocol static own4 { ipv4; route %s reject; }\n", as.Block)
	}
	if as.BlockV6 != "" {
		fmt.Fprintf(&bgp, "protocol static own6 { ipv6; route %s reject; }\n", as.BlockV6)
	}
	// The RPKI exercise needs a route whose origin is demonstrably wrong. FRR
	// originates it with `network`; BIRD needs an equally real route in its
	// RIB before BGP can export it. Omitting this made the mixed reference
	// appear to reject an invalid route that the lab never announced.
	if hijacker, prefix := svc.HijackOrigin(top); hijacker == as.ASN && prefix != "" && prefix != as.Block {
		fmt.Fprintf(&bgp, "protocol static hijack4 { ipv4; route %s reject; }\n", prefix)
	}
	bgp.WriteString("\n")

	// A one-router transit AS has no OSPF adjacency, so omit the protocol
	// rather than report a daemon configuration that has no interfaces to
	// carry it. Multi-router staff templates receive an ordinary area-zero
	// point-to-point OSPF configuration.
	var intra []string
	for _, iface := range d.Ifaces {
		if iface.Role == model.RoleIntraAS {
			intra = append(intra, iface.Name)
		}
	}
	sort.Strings(intra)
	if len(intra) > 0 {
		ospf.WriteString("protocol ospf v2 ospf4 {\n  ipv4 { import all; export all; };\n  area 0 {\n")
		for _, iface := range intra {
			fmt.Fprintf(&ospf, "    interface %q { type ptp; };\n", iface)
		}
		ospf.WriteString("  };\n}\n\n")
	}

	var peers []birdPeer

	// iBGP peers are loopback-sourced. Staff transit routers are usually
	// single-router, but supporting this form keeps BIRD honest about its
	// declared OSPF/BGP capability.
	if !as.InCore(d.Name) {
		for _, other := range as.Routers {
			if other == d || as.InCore(other.Name) {
				continue
			}
			loopback, ok := other.IfaceByName("lo")
			if !ok || loopback.Addr4 == "" {
				continue
			}
			peers = append(peers, birdPeer{
				name:    "ibgp_" + birdIdentifier(other.Name),
				address: addrOf(loopback.Addr4), asn: as.ASN, internal: true,
			})
		}
	}
	for _, iface := range d.Ifaces {
		if iface.Role != model.RoleInterAS && iface.Role != model.RoleIXPLink {
			continue
		}
		address, peerASN := "", 0
		if iface.Role == model.RoleIXPLink {
			address, peerASN = routeServerOn(top, iface)
		} else if iface.Peer != nil && iface.Peer.Device != nil {
			address, peerASN = addrOf(iface.Peer.Addr4), iface.Peer.Device.ASN
		}
		if address == "" || peerASN == 0 {
			continue
		}
		relationship := model.RelPeer
		if iface.Link != nil {
			relationship = iface.Link.PeerRelationship(iface)
		}
		peers = append(peers, birdPeer{
			name:         "ebgp_" + birdIdentifier(iface.Name),
			address:      address,
			asn:          peerASN,
			relationship: relationship,
			routeServer:  iface.Role == model.RoleIXPLink,
			slow:         iface.Role != model.RoleIXPLink && parseDelayMS(iface.Link) >= 25,
		})
		if iface.Role == model.RoleIXPLink {
			peers[len(peers)-1].ixpRecipients, peers[len(peers)-1].sameRegion =
				birdIXPPolicyMembers(top, as.ASN, peerASN, as.Region)
		}
	}
	sort.Slice(peers, func(i, j int) bool { return peers[i].name < peers[j].name })

	for _, peer := range peers {
		if peer.internal {
			continue
		}
		renderBirdFilters(&bgp, as.ASN, peer)
	}
	for _, peer := range peers {
		fmt.Fprintf(&bgp, "protocol bgp %s {\n", peer.name)
		fmt.Fprintf(&bgp, "  local as %d;\n", as.ASN)
		fmt.Fprintf(&bgp, "  neighbor %s as %d;\n", peer.address, peer.asn)
		if peer.internal {
			if local, ok := d.IfaceByName("lo"); ok && local.Addr4 != "" {
				fmt.Fprintf(&bgp, "  source address %s;\n", addrOf(local.Addr4))
			}
			bgp.WriteString("  ipv4 { import all; export all; };\n")
		} else {
			if peer.routeServer {
				// An exchange route server relays member paths rather than
				// inserting its own AS. BIRD's route-server client mode is
				// the portable equivalent of FRR's no-enforce-first-as.
				bgp.WriteString("  rs client;\n")
			}
			fmt.Fprintf(&bgp, "  ipv4 { import filter import_%s; export filter export_%s; };\n",
				peer.name, peer.name)
		}
		bgp.WriteString("}\n\n")
	}

	var expected strings.Builder
	into := func(domain, text string) {
		if text == "" {
			return
		}
		if as.Provides(domain) {
			platform.WriteString(text)
			return
		}
		expected.WriteString(text)
	}
	into(model.DomainOSPF, ospf.String())
	into(model.DomainBGP, bgp.String())

	return RouterConfig{Platform: platform.String(), Expected: expected.String()}, nil
}

func renderBirdFilters(b *strings.Builder, localASN int, peer birdPeer) {
	pref, community := 100, 30
	switch peer.relationship {
	case model.RelCustomer:
		pref, community = 300, 10
	case model.RelPeer:
		pref, community = 200, 20
	}
	if peer.slow {
		pref -= slowLinkPenalty
	}
	fmt.Fprintf(b, "filter import_%s {\n", peer.name)
	for _, asn := range peer.sameRegion {
		// FRR's IXP policy rejects a route that has already crossed another
		// student system in this region. BIRD's AS-path mask is the semantic
		// equivalent of the two FRR access-list spellings (terminal and
		// interior occurrence).
		// BIRD AS-path masks need the [= ... =] delimiters; bare [* ASN *]
		// is parsed as a literal list and rejects the whole configuration.
		fmt.Fprintf(b, "  if bgp_path ~ [= * %d * =] then reject;\n", asn)
	}
	fmt.Fprintf(b, "  bgp_local_pref = %d;\n", pref)
	fmt.Fprintf(b, "  bgp_community.add((1,%d));\n", community)
	b.WriteString("  accept;\n}\n")
	fmt.Fprintf(b, "filter export_%s {\n", peer.name)
	// FRR originates only the AS block, the declared hijack, and BGP-learned
	// routes. Exporting BIRD's direct/kernel link routes turns transport
	// subnets into Internet destinations and changes both policy and grading.
	b.WriteString("  if source != RTS_BGP && source != RTS_STATIC then reject;\n")
	if peer.relationship != model.RelCustomer {
		b.WriteString("  if (1,20) ~ bgp_community then reject;\n")
		b.WriteString("  if (1,30) ~ bgp_community then reject;\n")
	}
	for _, recipient := range peer.ixpRecipients {
		fmt.Fprintf(b, "  bgp_community.add((%d,%d));\n", peer.asn, recipient)
	}
	if peer.slow {
		for range 3 {
			fmt.Fprintf(b, "  bgp_path.prepend(%d);\n", localASN)
		}
	}
	b.WriteString("  accept;\n}\n\n")
}

// birdIXPPolicyMembers returns the export community target set and the
// same-region student ASNs that must not be re-imported from a route server.
// It mirrors ixpPolicy's topology-derived FRR behavior.
func birdIXPPolicyMembers(top *model.Topology, localASN, ixpASN int, region string) ([]int, []int) {
	var recipients, sameRegion []int
	for _, asn := range top.SortedASNs() {
		as := top.ASes[asn]
		if as == nil || asn == localASN || as.Role == model.RoleIXP || !attachedTo(top, asn, ixpASN) {
			continue
		}
		recipients = append(recipients, asn)
		if as.Role == model.RoleStudent && as.Region == region {
			sameRegion = append(sameRegion, asn)
		}
	}
	return recipients, sameRegion
}

func birdIdentifier(value string) string {
	var b strings.Builder
	for _, char := range value {
		switch {
		case char >= 'a' && char <= 'z', char >= 'A' && char <= 'Z', char >= '0' && char <= '9':
			b.WriteRune(char)
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "peer"
	}
	return b.String()
}
