package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/HongyuHe/twinet/internal/model"
)

type birdPeer struct {
	name, address string
	asn           int
	relationship  model.Relationship
	internal      bool
	routeServer   bool
}

// BirdRouter renders the BIRD 2 configuration used by staff/reference
// routers. Student-owned routers intentionally remain FRR-only while
// submissions are FRR command files; manifest validation explains that
// boundary before deploy.
//
// The configuration is derived from the same topology facts as FRR: kernel
// addresses are installed by birdRouterCommands, BIRD owns OSPF/BGP and the
// relationship policy, and Linux owns forwarding.
func BirdRouter(top *model.Topology, d *model.Device) (RouterConfig, error) {
	if d == nil || !d.IsRouter() {
		return RouterConfig{}, fmt.Errorf("BIRD configuration needs a router")
	}
	as := top.ASes[d.ASN]
	if as == nil {
		return RouterConfig{}, fmt.Errorf("%s belongs to unknown AS %d", d.ID, d.ASN)
	}
	if as.Role == model.RoleIXP {
		return RouterConfig{}, fmt.Errorf("%s is an IXP route server; BIRD route-server rendering is not supported", d.ID)
	}

	var b strings.Builder
	b.WriteString("# Generated by Twinet; do not edit while deployed.\n")
	fmt.Fprintf(&b, "router id %s;\n\n", routerID(d))
	b.WriteString("protocol device {}\n\n")
	b.WriteString("protocol direct direct4 { ipv4; }\n")
	b.WriteString("protocol direct direct6 { ipv6; }\n")
	b.WriteString("protocol kernel kernel4 { ipv4 { import none; export all; }; }\n")
	b.WriteString("protocol kernel kernel6 { ipv6 { import none; export all; }; }\n")
	if as.Block != "" {
		fmt.Fprintf(&b, "protocol static own4 { ipv4; route %s reject; }\n", as.Block)
	}
	if as.BlockV6 != "" {
		fmt.Fprintf(&b, "protocol static own6 { ipv6; route %s reject; }\n", as.BlockV6)
	}
	b.WriteString("\n")

	// A one-router transit AS has no OSPF adjacency, so omit the protocol
	// rather than report a daemon configuration that has no interfaces to
	// carry it. Multi-router staff templates receive an ordinary area-zero
	// point-to-point OSPF configuration.
	var intra []string
	for _, iface := range d.Ifaces {
		if iface.Role == model.RoleIntraAS {
			intra = append(intra, iface.Name)
		}
	}
	sort.Strings(intra)
	if len(intra) > 0 {
		b.WriteString("protocol ospf v2 ospf4 {\n  ipv4 { import all; export all; };\n  area 0 {\n")
		for _, iface := range intra {
			fmt.Fprintf(&b, "    interface %q { type ptp; };\n", iface)
		}
		b.WriteString("  };\n}\n\n")
	}

	var peers []birdPeer

	// iBGP peers are loopback-sourced. Staff transit routers are usually
	// single-router, but supporting this form keeps BIRD honest about its
	// declared OSPF/BGP capability.
	if !as.InCore(d.Name) {
		for _, other := range as.Routers {
			if other == d || as.InCore(other.Name) {
				continue
			}
			loopback, ok := other.IfaceByName("lo")
			if !ok || loopback.Addr4 == "" {
				continue
			}
			peers = append(peers, birdPeer{
				name:    "ibgp_" + birdIdentifier(other.Name),
				address: addrOf(loopback.Addr4), asn: as.ASN, internal: true,
			})
		}
	}
	for _, iface := range d.Ifaces {
		if iface.Role != model.RoleInterAS && iface.Role != model.RoleIXPLink {
			continue
		}
		address, peerASN := "", 0
		if iface.Role == model.RoleIXPLink {
			address, peerASN = routeServerOn(top, iface)
		} else if iface.Peer != nil && iface.Peer.Device != nil {
			address, peerASN = addrOf(iface.Peer.Addr4), iface.Peer.Device.ASN
		}
		if address == "" || peerASN == 0 {
			continue
		}
		relationship := model.RelPeer
		if iface.Link != nil {
			relationship = iface.Link.PeerRelationship(iface)
		}
		peers = append(peers, birdPeer{
			name:         "ebgp_" + birdIdentifier(iface.Name),
			address:      address,
			asn:          peerASN,
			relationship: relationship,
			routeServer:  iface.Role == model.RoleIXPLink,
		})
	}
	sort.Slice(peers, func(i, j int) bool { return peers[i].name < peers[j].name })

	for _, peer := range peers {
		if peer.internal {
			continue
		}
		renderBirdFilters(&b, peer)
	}
	for _, peer := range peers {
		fmt.Fprintf(&b, "protocol bgp %s {\n", peer.name)
		fmt.Fprintf(&b, "  local as %d;\n", as.ASN)
		fmt.Fprintf(&b, "  neighbor %s as %d;\n", peer.address, peer.asn)
		if peer.internal {
			if local, ok := d.IfaceByName("lo"); ok && local.Addr4 != "" {
				fmt.Fprintf(&b, "  source address %s;\n", addrOf(local.Addr4))
			}
			b.WriteString("  ipv4 { import all; export all; };\n")
		} else {
			if peer.routeServer {
				// An exchange route server relays member paths rather than
				// inserting its own AS. BIRD's route-server client mode is
				// the portable equivalent of FRR's no-enforce-first-as.
				b.WriteString("  rs client;\n")
			}
			fmt.Fprintf(&b, "  ipv4 { import filter import_%s; export filter export_%s; };\n",
				peer.name, peer.name)
		}
		b.WriteString("}\n\n")
	}

	// A BIRD reference router is always a platform-owned device. Keep this
	// split nevertheless so the provider contract remains explicit if a
	// future non-student managed role uses BIRD.
	if as.Role == model.RoleStudent {
		return RouterConfig{Expected: b.String()}, nil
	}
	return RouterConfig{Platform: b.String()}, nil
}

func renderBirdFilters(b *strings.Builder, peer birdPeer) {
	pref, community := 100, 30
	switch peer.relationship {
	case model.RelCustomer:
		pref, community = 300, 10
	case model.RelPeer:
		pref, community = 200, 20
	}
	fmt.Fprintf(b, "filter import_%s {\n", peer.name)
	fmt.Fprintf(b, "  bgp_local_pref = %d;\n", pref)
	fmt.Fprintf(b, "  bgp_community.add((1,%d));\n", community)
	b.WriteString("  accept;\n}\n")
	fmt.Fprintf(b, "filter export_%s {\n", peer.name)
	if peer.relationship != model.RelCustomer {
		b.WriteString("  if (1,20) ~ bgp_community then reject;\n")
		b.WriteString("  if (1,30) ~ bgp_community then reject;\n")
	}
	b.WriteString("  accept;\n}\n\n")
}

func birdIdentifier(value string) string {
	var b strings.Builder
	for _, char := range value {
		switch {
		case char >= 'a' && char <= 'z', char >= 'A' && char <= 'Z', char >= '0' && char <= '9':
			b.WriteRune(char)
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "peer"
	}
	return b.String()
}
