ARG BASE=twinet/router:msc-base
FROM ${BASE}
RUN apk add --no-cache coreutils procps python3
LABEL org.opencontainers.image.title="twinet-msc-router" \
      org.opencontainers.image.source="https://github.com/HongyuHe/Twinet"
