package fault

import (
	"context"
	"fmt"
	"net/netip"
	"strings"
)

// End-host failures and link failures.
//
// Twinet has an advantage over a hand-written fault library here: the model
// records the *correct* address for every interface, so an "incorrect IP" fault
// is generated by perturbing a known-good value rather than hard-coding one
// that might not even be plausible for the topology.

func init() {
	Register(&Fault{
		Name: "host_missing_ip", Category: CatEndHost, Needs: []Capability{CapIP},
		Symptom:  "Some hosts are unable to communicate with other devices in the network.",
		Describe: "The host's IPv4 address was removed from its interface.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			routes := saveRoutes(ctx, e, t)
			iface, addr, err := hostAddr(e, t)
			if err != nil {
				return nil, err
			}
			if _, err := e.Sh(ctx, t.DeviceID(), fmt.Sprintf("ip addr del %s dev %s", addr, iface)); err != nil {
				return nil, err
			}
			return State{"iface": iface, "addr": addr, "routes": routes}, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			// The interface must exist and be readable before its lack of an
			// address means anything.
			//
			// This asked whether the address was absent from output it did not
			// check it had received. A container that came back with no
			// interfaces at all satisfies that, and so does a probe that never
			// ran -- so the ground truth said "this host's address was removed"
			// while the real failure was that it had no wiring, and an agent
			// diagnosing it was being marked against a cause that was not
			// there.
			iface, addr := s["iface"], s["addr"]
			if iface == "" || addr == "" {
				return Evidence{}, fmt.Errorf("this fault did not record what it removed, "+
					"so it cannot be verified on %s", t.DeviceID())
			}
			out, code, err := e.TryE(ctx, t.DeviceID(), "ip -o link show dev "+iface)
			if err != nil {
				return Evidence{}, err
			}
			if code != 0 || strings.TrimSpace(out) == "" {
				return Evidence{
					Verified: false,
					Expected: "no address on " + iface,
					Observed: iface + " does not exist, which is a different fault entirely",
				}, nil
			}
			addrs, code, err := e.TryE(ctx, t.DeviceID(), "ip -o -4 addr show dev "+iface)
			if err != nil {
				return Evidence{}, err
			}
			if code != 0 {
				return Evidence{
					Verified: false,
					Expected: "no address on " + iface,
					Observed: "the interface could not be read, so nothing can be concluded",
				}, nil
			}
			gone := !strings.Contains(addrs, strings.SplitN(addr, "/", 2)[0])
			return Evidence{Verified: gone, Expected: "no address on " + iface,
				Observed: strings.TrimSpace(addrs)}, nil
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			if s["addr"] == "" {
				return nil
			}
			if _, err := e.Sh(ctx, t.DeviceID(),
				fmt.Sprintf("ip addr replace %s brd + dev %s", s["addr"], s["iface"])); err != nil {
				return err
			}
			return restoreRoutes(ctx, e, t, s["routes"])
		},
	})

	Register(&Fault{
		Name: "host_incorrect_ip", Category: CatEndHost, Needs: []Capability{CapIP},
		Symptom:  "Some hosts seem to be unreachable in the network.",
		Describe: "The host's IPv4 address was changed to one outside its subnet.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			routes := saveRoutes(ctx, e, t)
			iface, addr, err := hostAddr(e, t)
			if err != nil {
				return nil, err
			}
			wrong, err := perturbAddr(addr)
			if err != nil {
				return nil, err
			}
			// The undo is assembled before anything is changed, and returned
			// even when the change fails.
			//
			// These do `del` then `add`. A failure between the two leaves the
			// host with no address at all, and returning nil state meant the
			// engine had nothing to undo and nothing to record -- an
			// addressless host with an empty fault ledger, which is the state
			// that takes longest to explain.
			st := State{"iface": iface, "addr": addr, "wrong": wrong, "routes": routes}
			if _, err := e.Sh(ctx, t.DeviceID(), fmt.Sprintf(
				"ip addr del %s dev %s; ip addr add %s brd + dev %s", addr, iface, wrong, iface)); err != nil {
				return st, err
			}
			return st, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			// The injected address must be *there*, not merely the correct one
			// absent.
			//
			// Absence was the whole test, and a probe that could not run, or
			// an interface that no longer exists, satisfies it. After a
			// container restart the ground truth then said "this host has the
			// wrong address" while the real fault was that it had no wiring at
			// all -- and an agent scored against that truth is being marked on
			// a question nobody asked. Transport failures are no longer
			// swallowed either.
			return injectedAddressPresent(ctx, e, t, s)
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			if s["addr"] == "" {
				return nil
			}
			if _, err := e.Sh(ctx, t.DeviceID(), fmt.Sprintf(
				"ip addr del %s dev %s 2>/dev/null; ip addr replace %s brd + dev %s",
				s["wrong"], s["iface"], s["addr"], s["iface"])); err != nil {
				return err
			}
			return restoreRoutes(ctx, e, t, s["routes"])
		},
	})

	Register(&Fault{
		Name: "host_incorrect_netmask", Category: CatEndHost, Needs: []Capability{CapIP},
		Symptom:  "Some hosts seem to be unreachable in the network.",
		Describe: "The host's prefix length was widened, so it believes remote destinations are on-link.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			routes := saveRoutes(ctx, e, t)
			iface, addr, err := hostAddr(e, t)
			if err != nil {
				return nil, err
			}
			p, err := netip.ParsePrefix(addr)
			if err != nil {
				return nil, fmt.Errorf("%q is not addr/len: %w", addr, err)
			}
			bad := netip.PrefixFrom(p.Addr(), 8).String()
			// The undo is returned even when the change fails: see
			// host_incorrect_ip.
			st := State{"iface": iface, "addr": addr, "wrong": bad, "routes": routes}
			if _, err := e.Sh(ctx, t.DeviceID(), fmt.Sprintf(
				"ip addr del %s dev %s; ip addr add %s brd + dev %s", addr, iface, bad, iface)); err != nil {
				return st, err
			}
			return st, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			// Present, not merely absent: see host_incorrect_ip.
			return injectedAddressPresent(ctx, e, t, s)
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			if s["addr"] == "" {
				return nil
			}
			if _, err := e.Sh(ctx, t.DeviceID(), fmt.Sprintf(
				"ip addr del %s dev %s 2>/dev/null; ip addr replace %s brd + dev %s",
				s["wrong"], s["iface"], s["addr"], s["iface"])); err != nil {
				return err
			}
			return restoreRoutes(ctx, e, t, s["routes"])
		},
	})

	Register(&Fault{
		Name: "host_incorrect_gateway", Category: CatEndHost, Needs: []Capability{CapRoute},
		Symptom:  "Some hosts seem to be unreachable in the network.",
		Describe: "The host's default route was pointed at an address that does not forward.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			cur, _ := e.Try(ctx, t.DeviceID(), "ip route show default")
			cur = strings.TrimSpace(cur)
			// Refuse rather than destroy what cannot be put back.
			//
			// This used to inject regardless and resolve with
			// "ip route del default; if a baseline was recorded, restore it".
			// When nothing had been recorded the second half was skipped, so
			// resolving deleted the host's default route and put nothing back.
			// The fault then verified as resolved -- the bogus gateway really
			// was gone -- while the host was left permanently unable to leave
			// its own subnet, on a lab everyone believed was clean. It cost a
			// student a reachability mark before it was found.
			if cur == "" {
				return nil, fmt.Errorf(
					"%s has no default route to misdirect; injecting would leave it with none at all",
					t.DeviceID())
			}
			iface, addr, err := hostAddr(e, t)
			if err != nil {
				return nil, err
			}
			wrong, err := neighbourAddr(addr)
			if err != nil {
				return nil, err
			}
			_, err = e.Sh(ctx, t.DeviceID(), fmt.Sprintf(
				"ip route replace default via %s dev %s", wrong, iface))
			if err != nil {
				return nil, err
			}
			return State{"route": cur, "wrong": wrong}, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			out, _ := e.Try(ctx, t.DeviceID(), "ip route show default")
			// The predicate must name the wrong gateway. "A default route
			// exists" is true both while the fault is active and after it has
			// been put back, which made this fault permanently unresolvable.
			wrong := s["wrong"]
			if wrong == "" {
				_, addr, err := hostAddr(e, t)
				if err != nil {
					return Evidence{}, err
				}
				if wrong, err = neighbourAddr(addr); err != nil {
					return Evidence{}, err
				}
			}
			return Evidence{Verified: strings.Contains(out, "via "+wrong),
				Expected: "the default route via " + wrong, Observed: strings.TrimSpace(out)}, nil
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			if s["route"] == "" {
				return fmt.Errorf("no default route was recorded for %s, so it cannot be put back; "+
					"deleting the wrong one would leave the host with no route at all", t.DeviceID())
			}
			if _, err := e.Sh(ctx, t.DeviceID(),
				"ip route del default 2>/dev/null || true; ip route replace "+s["route"]); err != nil {
				return err
			}
			// Confirm the baseline is back, not merely that the wrong gateway
			// is gone. The two are not the same, and only one of them leaves
			// the host working.
			out, _ := e.Try(ctx, t.DeviceID(), "ip route show default")
			if strings.TrimSpace(out) == "" {
				return fmt.Errorf("%s was left with no default route after resolving", t.DeviceID())
			}
			return nil
		},
	})

	Register(&Fault{
		Name: "host_incorrect_dns", Category: CatEndHost, Needs: []Capability{CapFile, CapDNS},
		Symptom:  "Some hosts are unable to access web services.",
		Describe: "The host's resolver was pointed at an address that runs no DNS server.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			cur, _ := e.Try(ctx, t.DeviceID(), "cat /etc/resolv.conf 2>/dev/null")
			// Refuse rather than destroy what cannot be put back. If the
			// resolver file is unreadable or already empty, injecting would
			// guarantee that resolving leaves the host worse off than it
			// started, and the damage would be silent.
			if strings.TrimSpace(cur) == "" {
				return nil, fmt.Errorf(
					"%s has no readable /etc/resolv.conf to restore afterwards; refusing to inject",
					t.DeviceID())
			}
			// Truncate and rewrite rather than replace: the file is a bind
			// mount and cannot be unlinked.
			if _, err := e.Sh(ctx, t.DeviceID(),
				": > /etc/resolv.conf; printf 'nameserver 203.0.113.53\\n' >> /etc/resolv.conf"); err != nil {
				return nil, err
			}
			return State{"resolv": cur}, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			out, _ := e.Try(ctx, t.DeviceID(), "cat /etc/resolv.conf")
			return Evidence{Verified: strings.Contains(out, "203.0.113.53"),
				Observed: strings.TrimSpace(out)}, nil
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			// The file is never removed or replaced, only truncated and
			// rewritten. Docker bind-mounts /etc/resolv.conf into the
			// container, so unlinking it fails with "resource busy" and the
			// fault would be permanently unresolvable.
			body := strings.TrimSpace(s["resolv"])
			if body == "" {
				// Inject refuses to run without captured content, so this can
				// only be a record from an older build; emptying the file would
				// compound the damage rather than repair it.
				return fmt.Errorf("no saved resolver content for %s; refusing to empty the file",
					t.DeviceID())
			}
			script := ": > /etc/resolv.conf"
			for _, line := range strings.Split(body, "\n") {
				if strings.TrimSpace(line) == "" {
					continue
				}
				script += fmt.Sprintf("; printf '%%s\\n' %s >> /etc/resolv.conf", shellQuote(line))
			}
			_, err := e.Sh(ctx, t.DeviceID(), script)
			return err
		},
	})

	Register(&Fault{
		Name: "host_ip_conflict", Category: CatEndHost, Needs: []Capability{CapIP},
		Symptom:  "Some hosts experience intermittent connectivity issues.",
		Describe: "A second device was given the same address, so ARP resolves inconsistently.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			routes := saveRoutes(ctx, e, t)
			victim := t.Param("victim", "")
			if victim == "" {
				return nil, fmt.Errorf("host_ip_conflict needs a victim device in params")
			}
			vt := Target{AS: t.AS, Device: victim}
			_, addr, err := hostAddr(e, vt)
			if err != nil {
				return nil, err
			}
			iface, _, err := hostAddr(e, t)
			if err != nil {
				return nil, err
			}
			if _, err := e.Sh(ctx, t.DeviceID(),
				fmt.Sprintf("ip addr add %s brd + dev %s", addr, iface)); err != nil {
				return nil, err
			}
			return State{"iface": iface, "addr": addr, "routes": routes}, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			// The duplicate address must be present on the attacker, not merely
			// some address: every host has one of those.
			// Compared as addresses, not as text.
			//
			// A substring test says 5.105.0.1 is present on a device whose own
			// address is 5.105.0.10 -- or, worse, on the device that holds
			// 5.105.0.1 legitimately. The attacker's own address satisfied the
			// check, so the fault verified as present after it had been
			// resolved and the engine reported that the lab could not be put
			// back. Measured on this cluster.
			dup := strings.SplitN(s["addr"], "/", 2)[0]
			out, _ := e.Try(ctx, t.DeviceID(), "ip -o -4 addr show")
			victim, verr := netip.ParseAddr(dup)
			held := false
			if verr == nil {
				for _, line := range strings.Split(out, "\n") {
					for _, f := range strings.Fields(line) {
						p, err := netip.ParsePrefix(f)
						if err != nil {
							continue
						}
						if p.Addr() == victim && s["iface"] != "" &&
							strings.Contains(line, " "+s["iface"]+" ") {
							held = true
						}
					}
				}
			}
			return Evidence{Verified: held,
				Expected: "the victim's address " + dup + " also configured here",
				Observed: strings.TrimSpace(out)}, nil
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			if s["addr"] == "" {
				return nil
			}
			if _, err := e.Sh(ctx, t.DeviceID(),
				fmt.Sprintf("ip addr del %s dev %s 2>/dev/null || true", s["addr"], s["iface"])); err != nil {
				return err
			}
			// Removing an address can take a connected route with it, and every
			// route that resolved through it.
			return restoreRoutes(ctx, e, t, s["routes"])
		},
	})

	Register(&Fault{
		Name: "host_static_blackhole", Category: CatMisconfig, Needs: []Capability{CapRoute},
		Symptom:  "Traffic to part of the network disappears without an error.",
		Describe: "A static blackhole route was installed, silently discarding matching traffic.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			prefix := t.Prefix
			if prefix == "" {
				prefix = "0.0.0.0/1"
			}
			if _, err := e.Sh(ctx, t.DeviceID(), "ip route replace blackhole "+prefix); err != nil {
				return nil, err
			}
			return State{"prefix": prefix}, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			out, _ := e.Try(ctx, t.DeviceID(), "ip route show | grep blackhole")
			return Evidence{Verified: strings.Contains(out, "blackhole"),
				Observed: strings.TrimSpace(out)}, nil
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			if s["prefix"] == "" {
				return nil
			}
			_, err := e.Sh(ctx, t.DeviceID(),
				"ip route del blackhole "+s["prefix"]+" 2>/dev/null || true")
			return err
		},
	})
}

// hostAddr finds the interface and address a host fault should act on.
//
// The model is consulted first so the fault knows the *intended* address, and
// the live device only to confirm it. That is what lets an "incorrect address"
// be a perturbation of a correct one.
// shellQuote makes a string safe to embed in a shell command.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func hostAddr(e *Env, t Target) (iface, addr string, err error) {
	d, err := e.Device(t)
	if err != nil {
		return "", "", err
	}
	if t.Iface != "" {
		i, ok := d.IfaceByName(t.Iface)
		if !ok {
			return "", "", fmt.Errorf("device %s has no interface %q", d.ID, t.Iface)
		}
		if i.Addr4 == "" {
			return "", "", fmt.Errorf("%s:%s has no address in the plan", d.ID, i.Name)
		}
		return i.Name, i.Addr4, nil
	}
	for _, i := range d.Ifaces {
		if i.Name != "lo" && i.Addr4 != "" {
			return i.Name, i.Addr4, nil
		}
	}
	return "", "", fmt.Errorf("device %s has no addressed interface", d.ID)
}

// perturbAddr moves an address into a different /8, so it is unmistakably wrong
// rather than merely unusual.
func perturbAddr(addr string) (string, error) {
	p, err := netip.ParsePrefix(addr)
	if err != nil {
		return "", fmt.Errorf("%q is not addr/len: %w", addr, err)
	}
	b := p.Addr().As4()
	b[0] = 203
	b[1] = 0
	b[2] = 113
	return netip.PrefixFrom(netip.AddrFrom4(b), p.Bits()).String(), nil
}

// neighbourAddr returns an address on the same subnet that nothing answers for.
func neighbourAddr(addr string) (string, error) {
	p, err := netip.ParsePrefix(addr)
	if err != nil {
		return "", fmt.Errorf("%q is not addr/len: %w", addr, err)
	}
	b := p.Addr().As4()
	b[3] = 254
	return netip.AddrFrom4(b).String(), nil
}

// saveRoutes records the statically configured routes on a device.
//
// Removing an address takes its connected route with it, and the kernel then
// silently drops every route whose next hop that connected route resolved --
// including the default. Restoring the address does not bring them back, so a
// fault that only put the address back left the host able to talk to its own
// subnet and nothing else. That is how a host in this lab spent a week with no
// default route, and the reachability mark it cost was blamed on the student.
func saveRoutes(ctx context.Context, e *Env, t Target) string {
	out, _ := e.Try(ctx, t.DeviceID(),
		`ip -o route show 2>/dev/null | grep -v 'proto \(bgp\|ospf\|zebra\|kernel\)'`)
	var keep []string
	for _, l := range strings.Split(out, "\n") {
		if l = strings.TrimSpace(l); l != "" {
			keep = append(keep, l)
		}
	}
	return strings.Join(keep, "\n")
}

// restoreRoutes puts back what removing an address took with it.
func restoreRoutes(ctx context.Context, e *Env, t Target, saved string) error {
	for _, l := range strings.Split(saved, "\n") {
		if l = strings.TrimSpace(l); l == "" {
			continue
		}
		if _, err := e.Sh(ctx, t.DeviceID(), "ip route replace "+l); err != nil {
			return fmt.Errorf("putting back the route %q: %w", l, err)
		}
	}
	return nil
}

// injectedAddressPresent confirms the address a fault installed is on the
// interface it installed it on.
//
// These verifiers used to check that the *correct* address was absent, which a
// probe that could not run also satisfies, and so does an interface that no
// longer exists. After a container restart the ground truth then said "this
// host has the wrong address" while the real fault was that it had no wiring at
// all, and an agent scored against that truth is being marked on a question
// nobody asked.
func injectedAddressPresent(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
	iface, wrong := s["iface"], s["wrong"]
	if iface == "" || wrong == "" {
		return Evidence{}, fmt.Errorf("this fault did not record what it changed, so it "+
			"cannot be verified on %s", t.DeviceID())
	}
	out, code, err := e.TryE(ctx, t.DeviceID(), "ip -o -4 addr show dev "+iface)
	if err != nil {
		return Evidence{}, err
	}
	if code != 0 || strings.TrimSpace(out) == "" {
		return Evidence{
			Verified: false,
			Expected: wrong + " on " + iface,
			Observed: fmt.Sprintf("%s could not be read, so nothing can be concluded about it", iface),
		}, nil
	}
	return Evidence{
		Verified: strings.Contains(out, wrong),
		Expected: wrong + " on " + iface,
		Observed: strings.TrimSpace(out),
	}, nil
}
