package fault

import (
	"context"
	"fmt"
	"net/netip"
	"strings"
)

// End-host failures and link failures.
//
// Twinet has an advantage over a hand-written fault library here: the model
// records the *correct* address for every interface, so an "incorrect IP" fault
// is generated by perturbing a known-good value rather than hard-coding one
// that might not even be plausible for the topology.

func init() {
	Register(&Fault{
		Name: "host_missing_ip", Category: CatEndHost, Needs: []Capability{CapIP},
		Symptom:  "Some hosts are unable to communicate with other devices in the network.",
		Describe: "The host's IPv4 address was removed from its interface.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			iface, addr, err := hostAddr(e, t)
			if err != nil {
				return nil, err
			}
			if _, err := e.Sh(ctx, t.DeviceID(), fmt.Sprintf("ip addr del %s dev %s", addr, iface)); err != nil {
				return nil, err
			}
			return State{"iface": iface, "addr": addr}, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			iface, addr, err := hostAddr(e, t)
			if err != nil {
				return Evidence{}, err
			}
			out, _ := e.Try(ctx, t.DeviceID(), "ip -o -4 addr show dev "+iface)
			gone := !strings.Contains(out, strings.SplitN(addr, "/", 2)[0])
			return Evidence{Verified: gone, Expected: "no address on " + iface,
				Observed: strings.TrimSpace(out)}, nil
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			if s["addr"] == "" {
				return nil
			}
			_, err := e.Sh(ctx, t.DeviceID(),
				fmt.Sprintf("ip addr replace %s dev %s", s["addr"], s["iface"]))
			return err
		},
	})

	Register(&Fault{
		Name: "host_incorrect_ip", Category: CatEndHost, Needs: []Capability{CapIP},
		Symptom:  "Some hosts seem to be unreachable in the network.",
		Describe: "The host's IPv4 address was changed to one outside its subnet.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			iface, addr, err := hostAddr(e, t)
			if err != nil {
				return nil, err
			}
			wrong, err := perturbAddr(addr)
			if err != nil {
				return nil, err
			}
			_, err = e.Sh(ctx, t.DeviceID(), fmt.Sprintf(
				"ip addr del %s dev %s; ip addr add %s dev %s", addr, iface, wrong, iface))
			if err != nil {
				return nil, err
			}
			return State{"iface": iface, "addr": addr, "wrong": wrong}, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			iface, addr, err := hostAddr(e, t)
			if err != nil {
				return Evidence{}, err
			}
			out, _ := e.Try(ctx, t.DeviceID(), "ip -o -4 addr show dev "+iface)
			return Evidence{
				Verified: !strings.Contains(out, strings.SplitN(addr, "/", 2)[0]),
				Expected: "an address other than " + addr, Observed: strings.TrimSpace(out),
			}, nil
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			if s["addr"] == "" {
				return nil
			}
			_, err := e.Sh(ctx, t.DeviceID(), fmt.Sprintf(
				"ip addr del %s dev %s 2>/dev/null; ip addr replace %s dev %s",
				s["wrong"], s["iface"], s["addr"], s["iface"]))
			return err
		},
	})

	Register(&Fault{
		Name: "host_incorrect_netmask", Category: CatEndHost, Needs: []Capability{CapIP},
		Symptom:  "Some hosts seem to be unreachable in the network.",
		Describe: "The host's prefix length was widened, so it believes remote destinations are on-link.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			iface, addr, err := hostAddr(e, t)
			if err != nil {
				return nil, err
			}
			p, err := netip.ParsePrefix(addr)
			if err != nil {
				return nil, fmt.Errorf("%q is not addr/len: %w", addr, err)
			}
			bad := netip.PrefixFrom(p.Addr(), 8).String()
			_, err = e.Sh(ctx, t.DeviceID(), fmt.Sprintf(
				"ip addr del %s dev %s; ip addr add %s dev %s", addr, iface, bad, iface))
			if err != nil {
				return nil, err
			}
			return State{"iface": iface, "addr": addr, "wrong": bad}, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			iface, addr, err := hostAddr(e, t)
			if err != nil {
				return Evidence{}, err
			}
			out, _ := e.Try(ctx, t.DeviceID(), "ip -o -4 addr show dev "+iface)
			return Evidence{Verified: !strings.Contains(out, addr),
				Expected: "a prefix length other than " + addr, Observed: strings.TrimSpace(out)}, nil
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			if s["addr"] == "" {
				return nil
			}
			_, err := e.Sh(ctx, t.DeviceID(), fmt.Sprintf(
				"ip addr del %s dev %s 2>/dev/null; ip addr replace %s dev %s",
				s["wrong"], s["iface"], s["addr"], s["iface"]))
			return err
		},
	})

	Register(&Fault{
		Name: "host_incorrect_gateway", Category: CatEndHost, Needs: []Capability{CapRoute},
		Symptom:  "Some hosts seem to be unreachable in the network.",
		Describe: "The host's default route was pointed at an address that does not forward.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			cur, _ := e.Try(ctx, t.DeviceID(), "ip route show default")
			cur = strings.TrimSpace(cur)
			iface, addr, err := hostAddr(e, t)
			if err != nil {
				return nil, err
			}
			wrong, err := neighbourAddr(addr)
			if err != nil {
				return nil, err
			}
			_, err = e.Sh(ctx, t.DeviceID(), fmt.Sprintf(
				"ip route replace default via %s dev %s", wrong, iface))
			if err != nil {
				return nil, err
			}
			return State{"route": cur, "wrong": wrong}, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			out, _ := e.Try(ctx, t.DeviceID(), "ip route show default")
			// The predicate must name the wrong gateway. "A default route
			// exists" is true both while the fault is active and after it has
			// been put back, which made this fault permanently unresolvable.
			wrong := s["wrong"]
			if wrong == "" {
				_, addr, err := hostAddr(e, t)
				if err != nil {
					return Evidence{}, err
				}
				if wrong, err = neighbourAddr(addr); err != nil {
					return Evidence{}, err
				}
			}
			return Evidence{Verified: strings.Contains(out, "via "+wrong),
				Expected: "the default route via " + wrong, Observed: strings.TrimSpace(out)}, nil
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			script := "ip route del default 2>/dev/null || true"
			if s["route"] != "" {
				script += "; ip route replace " + s["route"]
			}
			_, err := e.Sh(ctx, t.DeviceID(), script)
			return err
		},
	})

	Register(&Fault{
		Name: "host_incorrect_dns", Category: CatEndHost, Needs: []Capability{CapFile, CapDNS},
		Symptom:  "Some hosts are unable to access web services.",
		Describe: "The host's resolver was pointed at an address that runs no DNS server.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			cur, _ := e.Try(ctx, t.DeviceID(), "cat /etc/resolv.conf 2>/dev/null")
			// Refuse rather than destroy what cannot be put back. If the
			// resolver file is unreadable or already empty, injecting would
			// guarantee that resolving leaves the host worse off than it
			// started, and the damage would be silent.
			if strings.TrimSpace(cur) == "" {
				return nil, fmt.Errorf(
					"%s has no readable /etc/resolv.conf to restore afterwards; refusing to inject",
					t.DeviceID())
			}
			// Truncate and rewrite rather than replace: the file is a bind
			// mount and cannot be unlinked.
			if _, err := e.Sh(ctx, t.DeviceID(),
				": > /etc/resolv.conf; printf 'nameserver 203.0.113.53\\n' >> /etc/resolv.conf"); err != nil {
				return nil, err
			}
			return State{"resolv": cur}, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			out, _ := e.Try(ctx, t.DeviceID(), "cat /etc/resolv.conf")
			return Evidence{Verified: strings.Contains(out, "203.0.113.53"),
				Observed: strings.TrimSpace(out)}, nil
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			// The file is never removed or replaced, only truncated and
			// rewritten. Docker bind-mounts /etc/resolv.conf into the
			// container, so unlinking it fails with "resource busy" and the
			// fault would be permanently unresolvable.
			body := strings.TrimSpace(s["resolv"])
			if body == "" {
				// Inject refuses to run without captured content, so this can
				// only be a record from an older build; emptying the file would
				// compound the damage rather than repair it.
				return fmt.Errorf("no saved resolver content for %s; refusing to empty the file",
					t.DeviceID())
			}
			script := ": > /etc/resolv.conf"
			for _, line := range strings.Split(body, "\n") {
				if strings.TrimSpace(line) == "" {
					continue
				}
				script += fmt.Sprintf("; printf '%%s\\n' %s >> /etc/resolv.conf", shellQuote(line))
			}
			_, err := e.Sh(ctx, t.DeviceID(), script)
			return err
		},
	})

	Register(&Fault{
		Name: "host_ip_conflict", Category: CatEndHost, Needs: []Capability{CapIP},
		Symptom:  "Some hosts experience intermittent connectivity issues.",
		Describe: "A second device was given the same address, so ARP resolves inconsistently.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			victim := t.Param("victim", "")
			if victim == "" {
				return nil, fmt.Errorf("host_ip_conflict needs a victim device in params")
			}
			vt := Target{AS: t.AS, Device: victim}
			_, addr, err := hostAddr(e, vt)
			if err != nil {
				return nil, err
			}
			iface, _, err := hostAddr(e, t)
			if err != nil {
				return nil, err
			}
			if _, err := e.Sh(ctx, t.DeviceID(),
				fmt.Sprintf("ip addr add %s dev %s", addr, iface)); err != nil {
				return nil, err
			}
			return State{"iface": iface, "addr": addr}, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			// The duplicate address must be present on the attacker, not merely
			// some address: every host has one of those.
			dup := strings.SplitN(s["addr"], "/", 2)[0]
			out, _ := e.Try(ctx, t.DeviceID(), "ip -o -4 addr show")
			return Evidence{Verified: dup != "" && strings.Contains(out, dup),
				Expected: "the victim's address " + dup + " also configured here",
				Observed: strings.TrimSpace(out)}, nil
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			if s["addr"] == "" {
				return nil
			}
			_, err := e.Sh(ctx, t.DeviceID(),
				fmt.Sprintf("ip addr del %s dev %s 2>/dev/null || true", s["addr"], s["iface"]))
			return err
		},
	})

	Register(&Fault{
		Name: "host_static_blackhole", Category: CatMisconfig, Needs: []Capability{CapRoute},
		Symptom:  "Traffic to part of the network disappears without an error.",
		Describe: "A static blackhole route was installed, silently discarding matching traffic.",
		Inject: func(ctx context.Context, e *Env, t Target) (State, error) {
			prefix := t.Prefix
			if prefix == "" {
				prefix = "0.0.0.0/1"
			}
			if _, err := e.Sh(ctx, t.DeviceID(), "ip route replace blackhole "+prefix); err != nil {
				return nil, err
			}
			return State{"prefix": prefix}, nil
		},
		Verify: func(ctx context.Context, e *Env, t Target, s State) (Evidence, error) {
			out, _ := e.Try(ctx, t.DeviceID(), "ip route show | grep blackhole")
			return Evidence{Verified: strings.Contains(out, "blackhole"),
				Observed: strings.TrimSpace(out)}, nil
		},
		Resolve: func(ctx context.Context, e *Env, t Target, s State) error {
			if s["prefix"] == "" {
				return nil
			}
			_, err := e.Sh(ctx, t.DeviceID(),
				"ip route del blackhole "+s["prefix"]+" 2>/dev/null || true")
			return err
		},
	})
}

// hostAddr finds the interface and address a host fault should act on.
//
// The model is consulted first so the fault knows the *intended* address, and
// the live device only to confirm it. That is what lets an "incorrect address"
// be a perturbation of a correct one.
// shellQuote makes a string safe to embed in a shell command.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func hostAddr(e *Env, t Target) (iface, addr string, err error) {
	d, err := e.Device(t)
	if err != nil {
		return "", "", err
	}
	if t.Iface != "" {
		i, ok := d.IfaceByName(t.Iface)
		if !ok {
			return "", "", fmt.Errorf("device %s has no interface %q", d.ID, t.Iface)
		}
		if i.Addr4 == "" {
			return "", "", fmt.Errorf("%s:%s has no address in the plan", d.ID, i.Name)
		}
		return i.Name, i.Addr4, nil
	}
	for _, i := range d.Ifaces {
		if i.Name != "lo" && i.Addr4 != "" {
			return i.Name, i.Addr4, nil
		}
	}
	return "", "", fmt.Errorf("device %s has no addressed interface", d.ID)
}

// perturbAddr moves an address into a different /8, so it is unmistakably wrong
// rather than merely unusual.
func perturbAddr(addr string) (string, error) {
	p, err := netip.ParsePrefix(addr)
	if err != nil {
		return "", fmt.Errorf("%q is not addr/len: %w", addr, err)
	}
	b := p.Addr().As4()
	b[0] = 203
	b[1] = 0
	b[2] = 113
	return netip.PrefixFrom(netip.AddrFrom4(b), p.Bits()).String(), nil
}

// neighbourAddr returns an address on the same subnet that nothing answers for.
func neighbourAddr(addr string) (string, error) {
	p, err := netip.ParsePrefix(addr)
	if err != nil {
		return "", fmt.Errorf("%q is not addr/len: %w", addr, err)
	}
	b := p.Addr().As4()
	b[3] = 254
	return netip.AddrFrom4(b).String(), nil
}
